// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stream_service.proto

#include "stream_service.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace opencv {
PROTOBUF_CONSTEXPR OcvMat::OcvMat(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.mat_data_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.rows_)*/0
  , /*decltype(_impl_.cols_)*/0
  , /*decltype(_impl_.elt_type_)*/0
  , /*decltype(_impl_.elt_size_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct OcvMatDefaultTypeInternal {
  PROTOBUF_CONSTEXPR OcvMatDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~OcvMatDefaultTypeInternal() {}
  union {
    OcvMat _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 OcvMatDefaultTypeInternal _OcvMat_default_instance_;
}  // namespace opencv
static ::_pb::Metadata file_level_metadata_stream_5fservice_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_stream_5fservice_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_stream_5fservice_2eproto = nullptr;

const uint32_t TableStruct_stream_5fservice_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::opencv::OcvMat, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::opencv::OcvMat, _impl_.rows_),
  PROTOBUF_FIELD_OFFSET(::opencv::OcvMat, _impl_.cols_),
  PROTOBUF_FIELD_OFFSET(::opencv::OcvMat, _impl_.elt_type_),
  PROTOBUF_FIELD_OFFSET(::opencv::OcvMat, _impl_.elt_size_),
  PROTOBUF_FIELD_OFFSET(::opencv::OcvMat, _impl_.mat_data_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::opencv::OcvMat)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::opencv::_OcvMat_default_instance_._instance,
};

const char descriptor_table_protodef_stream_5fservice_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\024stream_service.proto\022\006opencv\032\033google/p"
  "rotobuf/empty.proto\"Z\n\006OcvMat\022\014\n\004rows\030\001 "
  "\001(\005\022\014\n\004cols\030\002 \001(\005\022\020\n\010elt_type\030\003 \001(\005\022\020\n\010e"
  "lt_size\030\004 \001(\005\022\020\n\010mat_data\030\005 \001(\0142I\n\rStrea"
  "mService\0228\n\nSendStream\022\016.opencv.OcvMat\032\026"
  ".google.protobuf.Empty\"\000(\001b\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_stream_5fservice_2eproto_deps[1] = {
  &::descriptor_table_google_2fprotobuf_2fempty_2eproto,
};
static ::_pbi::once_flag descriptor_table_stream_5fservice_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_stream_5fservice_2eproto = {
    false, false, 234, descriptor_table_protodef_stream_5fservice_2eproto,
    "stream_service.proto",
    &descriptor_table_stream_5fservice_2eproto_once, descriptor_table_stream_5fservice_2eproto_deps, 1, 1,
    schemas, file_default_instances, TableStruct_stream_5fservice_2eproto::offsets,
    file_level_metadata_stream_5fservice_2eproto, file_level_enum_descriptors_stream_5fservice_2eproto,
    file_level_service_descriptors_stream_5fservice_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_stream_5fservice_2eproto_getter() {
  return &descriptor_table_stream_5fservice_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_stream_5fservice_2eproto(&descriptor_table_stream_5fservice_2eproto);
namespace opencv {

// ===================================================================

class OcvMat::_Internal {
 public:
};

OcvMat::OcvMat(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:opencv.OcvMat)
}
OcvMat::OcvMat(const OcvMat& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  OcvMat* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.mat_data_){}
    , decltype(_impl_.rows_){}
    , decltype(_impl_.cols_){}
    , decltype(_impl_.elt_type_){}
    , decltype(_impl_.elt_size_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.mat_data_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.mat_data_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_mat_data().empty()) {
    _this->_impl_.mat_data_.Set(from._internal_mat_data(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.rows_, &from._impl_.rows_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.elt_size_) -
    reinterpret_cast<char*>(&_impl_.rows_)) + sizeof(_impl_.elt_size_));
  // @@protoc_insertion_point(copy_constructor:opencv.OcvMat)
}

inline void OcvMat::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.mat_data_){}
    , decltype(_impl_.rows_){0}
    , decltype(_impl_.cols_){0}
    , decltype(_impl_.elt_type_){0}
    , decltype(_impl_.elt_size_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.mat_data_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.mat_data_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

OcvMat::~OcvMat() {
  // @@protoc_insertion_point(destructor:opencv.OcvMat)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void OcvMat::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.mat_data_.Destroy();
}

void OcvMat::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void OcvMat::Clear() {
// @@protoc_insertion_point(message_clear_start:opencv.OcvMat)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.mat_data_.ClearToEmpty();
  ::memset(&_impl_.rows_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.elt_size_) -
      reinterpret_cast<char*>(&_impl_.rows_)) + sizeof(_impl_.elt_size_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* OcvMat::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 rows = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.rows_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 cols = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.cols_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 elt_type = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.elt_type_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 elt_size = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.elt_size_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bytes mat_data = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          auto str = _internal_mutable_mat_data();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* OcvMat::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:opencv.OcvMat)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 rows = 1;
  if (this->_internal_rows() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_rows(), target);
  }

  // int32 cols = 2;
  if (this->_internal_cols() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(2, this->_internal_cols(), target);
  }

  // int32 elt_type = 3;
  if (this->_internal_elt_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(3, this->_internal_elt_type(), target);
  }

  // int32 elt_size = 4;
  if (this->_internal_elt_size() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(4, this->_internal_elt_size(), target);
  }

  // bytes mat_data = 5;
  if (!this->_internal_mat_data().empty()) {
    target = stream->WriteBytesMaybeAliased(
        5, this->_internal_mat_data(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:opencv.OcvMat)
  return target;
}

size_t OcvMat::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:opencv.OcvMat)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes mat_data = 5;
  if (!this->_internal_mat_data().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_mat_data());
  }

  // int32 rows = 1;
  if (this->_internal_rows() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_rows());
  }

  // int32 cols = 2;
  if (this->_internal_cols() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_cols());
  }

  // int32 elt_type = 3;
  if (this->_internal_elt_type() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_elt_type());
  }

  // int32 elt_size = 4;
  if (this->_internal_elt_size() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_elt_size());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData OcvMat::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    OcvMat::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*OcvMat::GetClassData() const { return &_class_data_; }


void OcvMat::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<OcvMat*>(&to_msg);
  auto& from = static_cast<const OcvMat&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:opencv.OcvMat)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_mat_data().empty()) {
    _this->_internal_set_mat_data(from._internal_mat_data());
  }
  if (from._internal_rows() != 0) {
    _this->_internal_set_rows(from._internal_rows());
  }
  if (from._internal_cols() != 0) {
    _this->_internal_set_cols(from._internal_cols());
  }
  if (from._internal_elt_type() != 0) {
    _this->_internal_set_elt_type(from._internal_elt_type());
  }
  if (from._internal_elt_size() != 0) {
    _this->_internal_set_elt_size(from._internal_elt_size());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void OcvMat::CopyFrom(const OcvMat& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:opencv.OcvMat)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool OcvMat::IsInitialized() const {
  return true;
}

void OcvMat::InternalSwap(OcvMat* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.mat_data_, lhs_arena,
      &other->_impl_.mat_data_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(OcvMat, _impl_.elt_size_)
      + sizeof(OcvMat::_impl_.elt_size_)
      - PROTOBUF_FIELD_OFFSET(OcvMat, _impl_.rows_)>(
          reinterpret_cast<char*>(&_impl_.rows_),
          reinterpret_cast<char*>(&other->_impl_.rows_));
}

::PROTOBUF_NAMESPACE_ID::Metadata OcvMat::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_stream_5fservice_2eproto_getter, &descriptor_table_stream_5fservice_2eproto_once,
      file_level_metadata_stream_5fservice_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace opencv
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::opencv::OcvMat*
Arena::CreateMaybeMessage< ::opencv::OcvMat >(Arena* arena) {
  return Arena::CreateMessageInternal< ::opencv::OcvMat >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
