// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: stream_service.proto

#include "stream_service.pb.h"
#include "stream_service.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace opencv {

static const char* StreamService_method_names[] = {
  "/opencv.StreamService/GetMat",
};

std::unique_ptr< StreamService::Stub> StreamService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< StreamService::Stub> stub(new StreamService::Stub(channel, options));
  return stub;
}

StreamService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_GetMat_(StreamService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  {}

::grpc::ClientReader< ::opencv::GetMatResponse>* StreamService::Stub::GetMatRaw(::grpc::ClientContext* context, const ::opencv::GetMatRequest& request) {
  return ::grpc::internal::ClientReaderFactory< ::opencv::GetMatResponse>::Create(channel_.get(), rpcmethod_GetMat_, context, request);
}

void StreamService::Stub::async::GetMat(::grpc::ClientContext* context, const ::opencv::GetMatRequest* request, ::grpc::ClientReadReactor< ::opencv::GetMatResponse>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::opencv::GetMatResponse>::Create(stub_->channel_.get(), stub_->rpcmethod_GetMat_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::opencv::GetMatResponse>* StreamService::Stub::AsyncGetMatRaw(::grpc::ClientContext* context, const ::opencv::GetMatRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::opencv::GetMatResponse>::Create(channel_.get(), cq, rpcmethod_GetMat_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::opencv::GetMatResponse>* StreamService::Stub::PrepareAsyncGetMatRaw(::grpc::ClientContext* context, const ::opencv::GetMatRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::opencv::GetMatResponse>::Create(channel_.get(), cq, rpcmethod_GetMat_, context, request, false, nullptr);
}

StreamService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      StreamService_method_names[0],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< StreamService::Service, ::opencv::GetMatRequest, ::opencv::GetMatResponse>(
          [](StreamService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::opencv::GetMatRequest* req,
             ::grpc::ServerWriter<::opencv::GetMatResponse>* writer) {
               return service->GetMat(ctx, req, writer);
             }, this)));
}

StreamService::Service::~Service() {
}

::grpc::Status StreamService::Service::GetMat(::grpc::ServerContext* context, const ::opencv::GetMatRequest* request, ::grpc::ServerWriter< ::opencv::GetMatResponse>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace opencv

