# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stream_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14stream_service.proto\x12\x0bgRPC_stream\"H\n\x06OcvMat\x12\x0c\n\x04rows\x18\x01 \x01(\x05\x12\x0c\n\x04\x63ols\x18\x02 \x01(\x05\x12\x10\n\x08\x65lt_type\x18\x03 \x01(\x05\x12\x10\n\x08mat_data\x18\x04 \x01(\x0c\"\x1f\n\rGetMatRequest\x12\x0e\n\x06status\x18\x01 \x01(\x08\"2\n\x0eGetMatResponse\x12 \n\x03mat\x18\x01 \x01(\x0b\x32\x13.gRPC_stream.OcvMat2V\n\rStreamService\x12\x45\n\x06GetMat\x12\x1a.gRPC_stream.GetMatRequest\x1a\x1b.gRPC_stream.GetMatResponse\"\x00\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stream_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _OCVMAT._serialized_start=37
  _OCVMAT._serialized_end=109
  _GETMATREQUEST._serialized_start=111
  _GETMATREQUEST._serialized_end=142
  _GETMATRESPONSE._serialized_start=144
  _GETMATRESPONSE._serialized_end=194
  _STREAMSERVICE._serialized_start=196
  _STREAMSERVICE._serialized_end=282
# @@protoc_insertion_point(module_scope)
